apiVersion: batch/v1
kind: Job
metadata:
  name: teste-memory
spec:
  template:
    spec:
      containers:
        - image: schwendler/orquestracao_ada_aula_6_memory:v1
          imagePullPolicy: Always
          name: teste-memory
          # resources:
          #   requests:
          #     memory: "100Mi"
          #   limits:
          #     memory: "200Mi"
      restartPolicy: OnFailure
    # backoffLimit: 4
status: {}
